extends Resource

var cacheTable = [
	"res://Scenes/rock.tscn",
	"res://Scenes/iron_rock.tscn",
	"res://Scenes/copper_rock.tscn",
	"res://Scenes/coal_rock.tscn",
	"res://Scenes/tree.tscn",
	"res://Scenes/oil_deposit.tscn",
	"res://Scenes/Displays/inventory_display_spaceship.tscn",
	"res://Scenes/resource_constructor.tscn",
	"res://Scenes/conveyor.tscn",
	"res://Scenes/conveyor_v2.tscn",
	"res://Scenes/vault.tscn",
	"res://Scenes/burner.tscn",
	"res://Scenes/mover.tscn",
	"res://Scenes/mover_long.tscn",
	"res://Scenes/tesla_coil.tscn",
	"res://Scenes/collector.tscn",
	"res://Scenes/bee.tscn",
	#"res://Scenes/refiner.tscn",
	"res://Scenes/chest.tscn",
	"res://Scenes/big_chest.tscn",
	"res://Scenes/splitter.tscn",
	"res://Scenes/splitter_v2.tscn",
	"res://Scenes/researcher.tscn",
	"res://Scenes/lamp.tscn",
	"res://Scenes/shredder.tscn",
	"res://Scenes/furnace.tscn",
	"res://Scenes/farm_plot.tscn",
	"res://Scenes/item.tscn",
	"res://Scenes/water_pump.tscn",
	"res://Scenes/oil_rig.tscn",
	"res://Scenes/boat.tscn",
	"res://Scenes/spaceship.tscn",
	"res://Scenes/storage_hub.tscn",
	"res://Scenes/underground_conveyor.tscn",
	"res://Scenes/underground_conveyor_v2.tscn",
	"res://Scenes/player.tscn",
	"res://Sprites/icon_products.png",
	"res://Sprites/icon_question_mark.png",
	"res://Sprites/icon_weapons.png",
	"res://Scenes/Displays/recipe_group_button.tscn",
	"res://Scenes/crafter_recipe_button.tscn",
	"res://Scenes/DungeonRooms/breakable_decoration.tscn",
	"res://Scenes/Displays/inventory_display_plaque.tscn",
	
	"res://Sprites/farm_plot.png",
	"res://Sprites/farm_plot_watered.png",
	"res://Scenes/effect_slash.tscn",
	"res://Scenes/attack_box.tscn",
	
	#dungeon rooms
	"res://Scenes/DungeonRooms/Regular/room_1.tscn",
	"res://Scenes/DungeonRooms/Regular/room_2.tscn",
	"res://Scenes/DungeonRooms/Regular/room_3.tscn",
	"res://Scenes/DungeonRooms/Regular/room_4.tscn",
	"res://Scenes/DungeonRooms/Regular/room_5.tscn",
	"res://Scenes/DungeonRooms/Regular/room_6.tscn",
	"res://Scenes/DungeonRooms/Regular/room_7.tscn",
	"res://Scenes/DungeonRooms/Regular/room_8.tscn",
	"res://Scenes/DungeonRooms/Required/boss_room_1.tscn",
	"res://Scenes/DungeonRooms/Required/exit.tscn",
	"res://Scenes/DungeonRooms/Special/special_room_chance.tscn",
	"res://Scenes/DungeonRooms/Special/special_room_chest.tscn",
	"res://Scenes/DungeonRooms/Special/special_room_pedestal.tscn",
	"res://Scenes/DungeonRooms/Special/special_room_resource.tscn",
	"res://Scenes/DungeonRooms/Special/special_room_wisdom.tscn",
	
	"res://Scenes/Enemies/mushroom_boss.tscn",
	"res://Scenes/Enemies/spore.tscn",
	"res://Scenes/trap_spikes.tscn",
	"res://Scenes/Enemies/mini_diadematus.tscn",
	
]
